name = "StudentIO"
uuid = "8b9e7a1c-4d5e-11ec-8c3e-0242ac120002"
version = "2.0.0"
authors = ["StudentIO Team"]

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OneHotArrays = "0b1bfda6-eb8a-41d2-88d8-f5af5cad476f"
Oxygen = "df9a0d86-3283-4920-82dc-4555fc0d1d8b"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[compat]
Distributions = "0.25.123"
Flux = "0.13"
HTTP = "1.9"
JSON3 = "1.13"
LinearAlgebra = "1.12.0"
OneHotArrays = "0.2.10"
Oxygen = "1.5"
Printf = "1.11.0"
Random = "1.11.0"
Statistics = "1.11.1"
Zygote = "0.7.10"
